apiVersion: apps/v1
kind: Deployment
metadata:
  name: todowebappclient-deployment
  labels:
    app: todowebappclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todowebappclient
  template:
    metadata:
      labels:
        app: todowebappclient
    spec:
      containers:
        - name: todowebappclient
          image: {{.Values.image.acrurl}}/todowebapp/todowebapp-client:{{.Values.image.tag}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ToDoAPIUrl
              valueFrom:
                configMapKeyRef:
                  name: todowebappapi-configmap
                  key: todowebappapi_url
          resources:
            requests:
              memory: 64Mi
              cpu: 200m
            limits:
              memory: 128Mi
              cpu: 400m
      # imagePullSecrets:
      #       - name: acr-pull
---
apiVersion: v1
kind: Service
metadata:
  name: todowebappclient-service
spec:
  # For test purpose, set to NodePort
  type: LoadBalancer
  selector:
    app: todowebappclient
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todowebappclient-hpa
spec:
  maxReplicas: 10 # define max replica count
  minReplicas: 2  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todowebappclient-deployment
  targetCPUUtilizationPercentage: 50 # target CPU utilization