apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: todostatestore
spec:
  type: state.mongodb
  version: v1
  initTimeout: 30s
  metadata:
    - name: host
      value: mongodbhost:27017
    - name: username
      value: user
    - name: password
      value: password
    - name: databaseName
      value: admin
