#apiVersion: dapr.io/v1alpha1
#kind: Component
#metadata:
#  name: querystatestore
#spec:
#  type: state.redis
#  version: v1
#  metadata:
#  - name: redisHost
#    value: redisjson:6379
#  - name: redisPassword
#    value: ""
#  - name: actorStateStore
#    value: "true"
#  - name: queryIndexes
#    value: |
#      [
#        {
#          "name": "todoIndex",
#          "indexes": [
#            {
#              "key": "id",
#              "type": "TEXT"
#            }
#          ]
#        }
#      ]      

#apiVersion: dapr.io/v1alpha1
#kind: Component
#metadata:
#  name: todostatestore
#spec:
#  type: state.azure.cosmosdb
#  version: v1
#  initTimeout: 30s
#  metadata:
#  - name: url
#    value: https://cosmosdbhost:8081/
#  - name: masterKey
#    value: "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="
#  - name: database
#    value: tasksmanagerdb
#  - name: collection
#    value: taskscollection
#scopes:
#- dapr-api

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: todostatestore
spec:
  type: state.mongodb
  version: v1
  initTimeout: 30s
  metadata:
    - name: host
      value: mongodbhost:27017
    - name: username
      value: user
    - name: password
      value: password
    - name: databaseName
      value: admin
