name: 04 CI/CD Terraform

on: 
  workflow_dispatch:
  push:
    paths: 
      - '04-AspNetCore_Terraform/terraform/**'
      - '.github/workflows/04-TF-cicd.yml'


jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{secrets.TF_04_ARM_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.TF_04_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.TF_04_ARM_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TF_04_ARM_TENANT_ID}}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: 04-AspNetCore_Terraform/terraform
        run: terraform init
        
      - name: Terraform Validate
        working-directory: 04-AspNetCore_Terraform/terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: 04-AspNetCore_Terraform/terraform
        run: terraform plan
        
      - name: Terraform Apply
        working-directory: 04-AspNetCore_Terraform/terraform
        run: terraform apply --auto-approve