name: 05-ACA-ToDo Web App Client-Build and deploy 
on:
  push:
    branches: [ "main" ]
    paths: 
      - '05-ContainerApps-Cosmos-GH/ToDoWebAppACA/ToDoWebApp.Client/**'
      - '.github/workflows/05-aca-client-cicd.yml'
    
  workflow_dispatch:

env:
  rgName: rg-todoacawebapp-dev1-we
  acaName: aca-client

permissions:
  id-token: write
  contents: read

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACA_05_ACR_LOGIN }}
          username: ${{ secrets.ACA_05_ACR_NAME }}
          password: ${{ secrets.ACA_05_ACR_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.ACA_05_ACR_LOGIN }}/${{ secrets.ACA_05_ACR_NAME }}/${{ env.acaName }}:${{ github.sha }} , ${{ secrets.ACA_05_ACR_LOGIN }}/${{ secrets.ACA_05_ACR_NAME }}/${{ env.acaName }}:latest
          file: 05-ContainerApps-Cosmos-GH/ToDoWebAppACA/ToDoWebApp.Client/Dockerfile
          context: 05-ContainerApps-Cosmos-GH/ToDoWebAppACA 

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
   
  #   steps:

      - name: Log in with Azure
        uses: Azure/login@v1
        with:
          # CLIENT_ID = Client ID of Service Principal
          # CLIENT_SECRET = Password created for this specific connection - this can further enhanced
          creds: '{"clientId":"${{ secrets.ACA_05_CLIENT_ID }}","clientSecret":"${{ secrets.ACA_05_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ACA_05_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ACA_05_TENANT_ID }}"}'



      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ${{ env.acaName }} -g ${{ env.rgName }} --server ${{ secrets.ACA_05_ACR_LOGIN }} --username  ${{ secrets.ACA_05_ACR_NAME }} --password ${{ secrets.ACA_05_ACR_PASSWORD }}
            az containerapp update -n ${{ env.acaName }} -g ${{ env.rgName }} --image ${{ secrets.ACA_05_ACR_LOGIN }}/${{ secrets.ACA_05_ACR_NAME }}/${{ env.acaName }}:${{ github.sha }}
  

      